# Generated by Django 6.0.3 on 2026-03-30 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BgRegleAlerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('libelle', models.CharField(max_length=200)),
                ('niveau', models.CharField(choices=[('critique', 'Critique'), ('haute', 'Haute'), ('moyenne', 'Moyenne')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('seuil', models.FloatField(blank=True, help_text='Seuil numérique si applicable', null=True)),
                ('active', models.BooleanField(default=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordre', 'code'],
            },
        ),
        migrations.CreateModel(
            name='BgImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_nom', models.CharField(max_length=255)),
                ('fichier_path', models.CharField(max_length=500)),
                ('exercice', models.IntegerField(help_text='Année comptable ex: 2025')),
                ('periode', models.IntegerField(help_text='Numéro de période G/L (1-16)')),
                ('date_import', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de traitement'), ('traitement', 'En cours de traitement'), ('traite', 'Traité — en attente validation'), ('valide', 'Validé par la DF'), ('rejete', 'Rejeté'), ('gele', 'Gelé — période clôturée')], default='en_attente', max_length=20)),
                ('nb_lignes', models.IntegerField(default=0)),
                ('nb_anomalies', models.IntegerField(default=0)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('commentaire_df', models.TextField(blank=True)),
                ('erreur_traitement', models.TextField(blank=True)),
                ('importe_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bg_imports', to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bg_validations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Import Balance Générale',
                'verbose_name_plural': 'Imports Balance Générale',
                'ordering': ['-date_import'],
                'unique_together': {('exercice', 'periode')},
            },
        ),
        migrations.CreateModel(
            name='BgComparaison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_compte', models.CharField(max_length=20)),
                ('entite', models.CharField(max_length=20)),
                ('total_courant', models.BigIntegerField(default=0)),
                ('total_precedent', models.BigIntegerField(default=0)),
                ('variation_absolue', models.BigIntegerField(default=0)),
                ('variation_pct', models.FloatField(blank=True, null=True)),
                ('is_variation_forte', models.BooleanField(default=False)),
                ('bg_import_courant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparaisons_courantes', to='balance_generale.bgimport')),
                ('bg_import_precedent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comparaisons_precedentes', to='balance_generale.bgimport')),
            ],
            options={
                'ordering': ['num_compte', 'entite'],
            },
        ),
        migrations.CreateModel(
            name='BgAuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('import', 'Import fichier'), ('validation', 'Validation DF'), ('rejet', 'Rejet'), ('gel', 'Gel période'), ('alerte', 'Traitement alerte'), ('export', 'Export rapport')], max_length=20)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('bg_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit', to='balance_generale.bgimport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BgAlerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('critique', 'Critique — bloque la validation'), ('haute', 'Haute — justification requise'), ('moyenne', 'Moyenne — surveillance'), ('info', 'Information')], max_length=10)),
                ('code_regle', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('num_compte', models.CharField(blank=True, max_length=20)),
                ('entite', models.CharField(blank=True, max_length=20)),
                ('valeur_constatee', models.BigIntegerField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('ouverte', 'Ouverte'), ('justifiee', 'Justifiée'), ('resolue', 'Résolue'), ('ignoree', 'Ignorée')], default='ouverte', max_length=15)),
                ('justification', models.TextField(blank=True)),
                ('traite_le', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_bg_traitees', to=settings.AUTH_USER_MODEL)),
                ('bg_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='balance_generale.bgimport')),
            ],
            options={
                'ordering': ['niveau', 'num_compte'],
            },
        ),
        migrations.CreateModel(
            name='BgAgregat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_agregat', models.CharField(choices=[('classe', 'Agrégat par classe'), ('bilan_actif', 'Bilan actif'), ('bilan_passif', 'Bilan passif'), ('resultat', 'Compte de résultat'), ('tresorerie', 'Trésorerie nette'), ('kpi', 'KPI calculé')], max_length=20)),
                ('entite', models.CharField(choices=[('CIE', 'CIE'), ('Secteur', 'Secteur'), ('Exploitant', 'Exploitant')], max_length=20)),
                ('libelle', models.CharField(max_length=100)),
                ('classe', models.IntegerField(blank=True, null=True)),
                ('valeur_report', models.BigIntegerField(default=0)),
                ('valeur_periode', models.BigIntegerField(default=0)),
                ('valeur_exercice', models.BigIntegerField(default=0)),
                ('valeur_total', models.BigIntegerField(default=0)),
                ('bg_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agregats', to='balance_generale.bgimport')),
            ],
            options={
                'ordering': ['entite', 'classe'],
            },
        ),
        migrations.CreateModel(
            name='BgLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_compte', models.CharField(max_length=20)),
                ('intitule', models.CharField(max_length=255)),
                ('classe', models.IntegerField()),
                ('entite', models.CharField(choices=[('CIE', 'CIE'), ('Secteur', 'Secteur'), ('Exploitant', 'Exploitant')], max_length=20)),
                ('report', models.BigIntegerField(default=0)),
                ('activite_periode', models.BigIntegerField(default=0)),
                ('activite_exercice', models.BigIntegerField(default=0)),
                ('total', models.BigIntegerField(default=0)),
                ('is_interco', models.BooleanField(default=False)),
                ('is_ran', models.BooleanField(default=False)),
                ('sens_normal', models.CharField(choices=[('D', 'Débiteur'), ('C', 'Créditeur')], default='D', max_length=1)),
                ('bg_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='balance_generale.bgimport')),
            ],
            options={
                'ordering': ['num_compte', 'entite'],
                'indexes': [models.Index(fields=['bg_import', 'entite'], name='balance_gen_bg_impo_af2cc7_idx'), models.Index(fields=['bg_import', 'classe'], name='balance_gen_bg_impo_8cf74b_idx'), models.Index(fields=['num_compte'], name='balance_gen_num_com_8ca6a1_idx')],
            },
        ),
    ]
