# Generated by Django 6.0.3 on 2026-03-26 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SousDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('libelle', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0, help_text="Ordre d'affichage dans la sidebar")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_directions_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sous-Direction',
                'verbose_name_plural': 'Sous-Directions',
                'ordering': ['ordre', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('libelle', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections_responsable', to=settings.AUTH_USER_MODEL)),
                ('sous_direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='organisation.sousdirection')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ['sous_direction', 'code'],
                'unique_together': {('sous_direction', 'code')},
            },
        ),
        migrations.CreateModel(
            name='PIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('libelle', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sous_direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pips', to='organisation.sousdirection')),
            ],
            options={
                'verbose_name': 'PIP',
                'verbose_name_plural': 'PIP',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='UtilisateurSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_principale', models.BooleanField(default=True, help_text="Section principale de l'utilisateur")),
                ('date_affectation', models.DateField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisateurs_lien', to='organisation.section')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections_lien', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Affectation Section',
                'verbose_name_plural': 'Affectations Sections',
                'unique_together': {('utilisateur', 'section')},
            },
        ),
    ]
