# Generated by Django 6.0.3 on 2026-03-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sousdirection',
            name='couleur',
            field=models.CharField(choices=[('#003F7F', 'Bleu CIE (défaut)'), ('#0056A8', 'Bleu clair'), ('#1a7cc1', 'Bleu azur'), ('#17a2b8', 'Cyan'), ('#28a745', 'Vert'), ('#20c997', 'Vert menthe'), ('#6f42c1', 'Violet'), ('#e83e8c', 'Rose'), ('#fd7e14', 'Orange'), ('#F5A623', 'Or CIE'), ('#dc3545', 'Rouge'), ('#6c757d', 'Gris')], default='#003F7F', help_text="Couleur d'identité visuelle de la sous-direction", max_length=7),
        ),
        migrations.AlterField(
            model_name='sousdirection',
            name='ordre',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='utilisateursection',
            name='est_principale',
            field=models.BooleanField(default=True),
        ),
    ]
