# Generated by Django 6.0.3 on 2026-03-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_sousdirection_couleur_alter_sousdirection_ordre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sousdirection',
            name='mission',
            field=models.TextField(blank=True, help_text='Décrivez la mission, les objectifs et les attentes de la sous-direction', verbose_name='Mission & objectifs stratégiques'),
        ),
        migrations.AlterField(
            model_name='sousdirection',
            name='couleur',
            field=models.CharField(choices=[('#003F7F', 'Bleu CIE (défaut)'), ('#0056A8', 'Bleu clair'), ('#1a7cc1', 'Bleu azur'), ('#17a2b8', 'Cyan'), ('#28a745', 'Vert'), ('#20c997', 'Vert menthe'), ('#6f42c1', 'Violet'), ('#e83e8c', 'Rose'), ('#fd7e14', 'Orange'), ('#F5A623', 'Or CIE'), ('#dc3545', 'Rouge'), ('#6c757d', 'Gris')], default='#003F7F', max_length=7),
        ),
        migrations.AlterField(
            model_name='sousdirection',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description générale'),
        ),
    ]
