# Generated by Django 6.0.3 on 2026-03-27 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0003_add_mission_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='N° de compte')),
                ('libelle', models.CharField(max_length=300)),
                ('type_compte', models.CharField(choices=[('actif', 'Actif'), ('passif', 'Passif'), ('charge', 'Charge'), ('produit', 'Produit'), ('tresorerie', 'Trésorerie'), ('tiers', 'Compte tiers'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Compte Comptable',
                'verbose_name_plural': 'Comptes Comptables',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='SousDirectionCompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, help_text='Précision sur le suivi de ce compte', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_directions', to='organisation.comptecomptable')),
                ('sous_direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes', to='organisation.sousdirection')),
            ],
            options={
                'verbose_name': 'Compte suivi SD',
                'verbose_name_plural': 'Comptes suivis SD',
                'ordering': ['compte__numero'],
                'unique_together': {('sous_direction', 'compte')},
            },
        ),
    ]
