# Generated by Django 6.0.3 on 2026-03-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0004_add_compte_comptable'),
    ]

    operations = [
        migrations.AddField(
            model_name='sousdirection',
            name='audio_resume',
            field=models.FileField(blank=True, help_text='Fichier audio résumant la sous-direction (MP3, WAV, OGG)', null=True, upload_to='audio/sd/', verbose_name='Audio de présentation'),
        ),
    ]
