# Generated by Django 6.0.3 on 2026-03-26 21:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisation', '0003_add_mission_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('type_activite', models.CharField(choices=[('ponctuelle', 'Ponctuelle'), ('mensuelle', 'Mensuelle récurrente'), ('trimestrielle', 'Trimestrielle')], default='ponctuelle', max_length=20)),
                ('statut', models.CharField(choices=[('ouverte', 'Ouverte'), ('en_cours', 'En cours'), ('en_attente', 'En attente'), ('cloturee', 'Clôturée')], default='ouverte', max_length=20)),
                ('date_ouverture', models.DateField(default=django.utils.timezone.now)),
                ('date_butoir', models.DateField(verbose_name='Date butoir (échéance)')),
                ('date_intermediaire', models.DateField(blank=True, null=True, verbose_name='Date intermédiaire')),
                ('date_intermediaire_init', models.DateField(blank=True, null=True, verbose_name='Date intermédiaire initiale')),
                ('date_realisation', models.DateField(blank=True, null=True, verbose_name='Date de réalisation effective')),
                ('nb_reports', models.PositiveSmallIntegerField(default=0)),
                ('etat_avancement', models.PositiveSmallIntegerField(default=0, help_text='0 à 100 %')),
                ('est_dans_delai', models.BooleanField(blank=True, help_text='True si clôturée avant ou à la date butoir', null=True)),
                ('est_kpi', models.BooleanField(default=False)),
                ('est_arrete', models.BooleanField(default=False, verbose_name='Arrêté comptable')),
                ('mois_reference', models.CharField(blank=True, help_text='YYYY-MM', max_length=7)),
                ('cloture_le', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('activite_parente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='operations.activite')),
                ('cloture_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites_cloturees', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites_creees', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='organisation.section')),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Activités',
                'ordering': ['date_butoir', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivitePIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=200)),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.activite')),
                ('pip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.pip')),
            ],
            options={
                'unique_together': {('activite', 'pip')},
            },
        ),
        migrations.AddField(
            model_name='activite',
            name='pips',
            field=models.ManyToManyField(blank=True, through='operations.ActivitePIP', to='organisation.pip'),
        ),
        migrations.CreateModel(
            name='AlerteMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alerte', models.CharField(choices=[('ouverture', 'Ouverture'), ('rappel', 'Rappel'), ('report', 'Report de date'), ('cloture', 'Clôture'), ('clonage', 'Clonage'), ('manuelle', 'Alerte manuelle')], max_length=20)),
                ('destinataires', models.TextField(help_text='Emails séparés par virgule')),
                ('envoye_le', models.DateTimeField(auto_now_add=True)),
                ('succes', models.BooleanField(default=True)),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='operations.activite')),
            ],
            options={
                'verbose_name': 'Alerte mail',
                'ordering': ['-envoye_le'],
            },
        ),
        migrations.CreateModel(
            name='CommentaireActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_comment', models.CharField(choices=[('commentaire', 'Commentaire'), ('mise_a_jour', 'Mise à jour'), ('alerte', 'Alerte'), ('cloture', 'Clôture')], default='commentaire', max_length=20)),
                ('contenu', models.TextField()),
                ('avancement', models.PositiveSmallIntegerField(default=0, help_text='Avancement déclaré au moment du commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='operations.activite')),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commentaire',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_responsable', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='organisation.section')),
            ],
            options={
                'verbose_name': 'Dossier',
                'verbose_name_plural': 'Dossiers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='activite',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='operations.dossier'),
        ),
        migrations.CreateModel(
            name='HistoriqueActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champ_modifie', models.CharField(max_length=100)),
                ('ancienne_valeur', models.TextField(blank=True)),
                ('nouvelle_valeur', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='operations.activite')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique activité',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActiviteActeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_activite', models.CharField(choices=[('responsable', 'Responsable'), ('acteur', 'Acteur')], default='acteur', max_length=20)),
                ('peut_recevoir_mail', models.BooleanField(default=True)),
                ('date_affectation', models.DateField(auto_now_add=True)),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acteurs', to='operations.activite')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites_acteur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Acteur d'activité",
                'unique_together': {('activite', 'utilisateur')},
            },
        ),
    ]
