# Generated by Django 6.0.2 on 2026-04-01 12:52

import apps.operations.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisation', '0005_add_audio_sd'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('libelle', models.CharField(max_length=300)),
                ('categorie', models.CharField(choices=[('rapport', 'Rapport'), ('balance', 'Balance / État comptable'), ('grand_livre', 'Grand Livre'), ('facture', 'Facture / Bordereau'), ('tableau', 'Tableau de bord / Synthèse'), ('proces_verbal', 'Procès-verbal / Compte-rendu'), ('situation', 'Situation financière'), ('autre', 'Autre document')], default='autre', max_length=30)),
                ('description', models.TextField(blank=True, help_text='Précisions sur ce type de document')),
                ('actif', models.BooleanField(default=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Type de document',
                'verbose_name_plural': 'Types de documents',
                'ordering': ['categorie', 'ordre', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('type_activite', models.CharField(choices=[('ponctuelle', 'Ponctuelle'), ('mensuelle', 'Mensuelle récurrente'), ('trimestrielle', 'Trimestrielle')], default='ponctuelle', max_length=20)),
                ('statut', models.CharField(choices=[('ouverte', 'Ouverte'), ('en_cours', 'En cours'), ('en_attente', 'En attente'), ('cloturee', 'Clôturée')], default='ouverte', max_length=20)),
                ('date_ouverture', models.DateField(default=django.utils.timezone.now)),
                ('date_butoir', models.DateField(verbose_name='Date butoir (échéance)')),
                ('date_intermediaire', models.DateField(blank=True, null=True, verbose_name='Date intermédiaire')),
                ('date_intermediaire_init', models.DateField(blank=True, null=True, verbose_name='Date intermédiaire initiale')),
                ('date_realisation', models.DateField(blank=True, null=True, verbose_name='Date de réalisation effective')),
                ('nb_reports', models.PositiveSmallIntegerField(default=0)),
                ('etat_avancement', models.PositiveSmallIntegerField(default=0, help_text='0 à 100 %')),
                ('est_dans_delai', models.BooleanField(blank=True, help_text='True si clôturée avant ou à la date butoir', null=True)),
                ('est_kpi', models.BooleanField(default=False)),
                ('est_arrete', models.BooleanField(default=False, verbose_name='Arrêté comptable')),
                ('mois_reference', models.CharField(blank=True, help_text='YYYY-MM', max_length=7)),
                ('cloture_le', models.DateTimeField(blank=True, null=True)),
                ('cloture_motif', models.CharField(blank=True, choices=[('objectif_atteint', 'Objectif atteint ✓'), ('partiellement', 'Partiellement atteint'), ('non_atteint', 'Objectif non atteint'), ('annule', 'Activité annulée'), ('autre', 'Autre motif')], max_length=30, null=True, verbose_name='Motif de clôture')),
                ('cloture_commentaire', models.TextField(blank=True, verbose_name='Commentaire de clôture')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('activite_parente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='operations.activite')),
                ('cloture_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites_cloturees', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites_creees', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='organisation.section')),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Activités',
                'ordering': ['date_butoir', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivitePIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=200)),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.activite')),
                ('pip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.pip')),
            ],
            options={
                'unique_together': {('activite', 'pip')},
            },
        ),
        migrations.AddField(
            model_name='activite',
            name='pips',
            field=models.ManyToManyField(blank=True, through='operations.ActivitePIP', to='organisation.pip'),
        ),
        migrations.CreateModel(
            name='AlerteMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alerte', models.CharField(choices=[('ouverture', 'Ouverture'), ('rappel', 'Rappel'), ('report', 'Report de date'), ('cloture', 'Clôture'), ('clonage', 'Clonage'), ('manuelle', 'Alerte manuelle')], max_length=20)),
                ('destinataires', models.TextField(help_text='Emails séparés par virgule')),
                ('envoye_le', models.DateTimeField(auto_now_add=True)),
                ('succes', models.BooleanField(default=True)),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='operations.activite')),
            ],
            options={
                'verbose_name': 'Alerte mail',
                'ordering': ['-envoye_le'],
            },
        ),
        migrations.CreateModel(
            name='CommentaireActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_comment', models.CharField(choices=[('commentaire', 'Commentaire'), ('mise_a_jour', 'Mise à jour'), ('alerte', 'Alerte'), ('cloture', 'Clôture')], default='commentaire', max_length=20)),
                ('contenu', models.TextField()),
                ('avancement', models.PositiveSmallIntegerField(default=0, help_text='Avancement déclaré au moment du commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='operations.activite')),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commentaire',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.CharField(choices=[('non_commence', 'Non commencé'), ('en_cours', 'En cours de production'), ('finalise', 'Finalisé'), ('valide', 'Validé'), ('non_produit', 'Non produit')], default='non_commence', max_length=20)),
                ('observations', models.TextField(blank=True, help_text="Commentaires sur l'état de production")),
                ('date_prevue', models.DateField(blank=True, null=True, verbose_name='Date de production prévue')),
                ('date_realisation', models.DateField(blank=True, null=True, verbose_name='Date de réalisation effective')),
                ('mis_a_jour_le', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='operations.activite')),
                ('mis_a_jour_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_mis_a_jour', to=settings.AUTH_USER_MODEL)),
                ('type_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activite_docs', to='operations.typedocument')),
            ],
            options={
                'verbose_name': 'Document attendu',
                'verbose_name_plural': 'Documents attendus',
                'ordering': ['type_document__categorie', 'type_document__ordre'],
                'unique_together': {('activite', 'type_document')},
            },
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_responsable', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='organisation.section')),
            ],
            options={
                'verbose_name': 'Dossier',
                'verbose_name_plural': 'Dossiers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='activite',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='operations.dossier'),
        ),
        migrations.CreateModel(
            name='HistoriqueActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champ_modifie', models.CharField(max_length=100)),
                ('ancienne_valeur', models.TextField(blank=True)),
                ('nouvelle_valeur', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='operations.activite')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique activité',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstructionTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='operations/instructions/')),
                ('nom_original', models.CharField(max_length=255)),
                ('taille_octets', models.PositiveIntegerField(default=0)),
                ('ajoute_le', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, help_text="Titre ou description courte de l'instruction", max_length=200)),
                ('ajoute_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructions_ajoutees', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='operations.documentactivite')),
            ],
            options={
                'verbose_name': 'Instruction de travail',
                'verbose_name_plural': 'Instructions de travail',
                'ordering': ['ajoute_le'],
            },
        ),
        migrations.CreateModel(
            name='ActiviteActeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_activite', models.CharField(choices=[('responsable', 'Responsable'), ('acteur', 'Acteur')], default='acteur', max_length=20)),
                ('peut_recevoir_mail', models.BooleanField(default=True)),
                ('date_affectation', models.DateField(auto_now_add=True)),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acteurs', to='operations.activite')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites_acteur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Acteur d'activité",
                'unique_together': {('activite', 'utilisateur')},
            },
        ),
    ]
