# Generated by Django 6.0.3 on 2026-03-26 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial_operations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='cloture_commentaire',
            field=models.TextField(blank=True, verbose_name='Commentaire de clôture'),
        ),
        migrations.AddField(
            model_name='activite',
            name='cloture_motif',
            field=models.CharField(blank=True, choices=[('objectif_atteint', 'Objectif atteint ✓'), ('partiellement', 'Partiellement atteint'), ('non_atteint', 'Objectif non atteint'), ('annule', 'Activité annulée'), ('autre', 'Autre motif')], max_length=30, null=True, verbose_name='Motif de clôture'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=300, verbose_name='Intitulé du document')),
                ('description', models.TextField(blank=True, verbose_name='Description / observations')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('transfere', 'Transféré'), ('realise', 'Réalisé'), ('archive', 'Archivé')], default='en_attente', max_length=20)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='documents/activites/')),
                ('date_echeance', models.DateField(blank=True, null=True, verbose_name="Date d'échéance doc.")),
                ('transfere_le', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='operations.activite')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_crees', to=settings.AUTH_USER_MODEL)),
                ('transfere_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_transferes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['libelle'],
            },
        ),
    ]
