# Generated by Django 6.0.2 on 2026-03-27 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial_operations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('libelle', models.CharField(max_length=300)),
                ('categorie', models.CharField(choices=[('rapport', 'Rapport'), ('balance', 'Balance / État comptable'), ('grand_livre', 'Grand Livre'), ('facture', 'Facture / Bordereau'), ('tableau', 'Tableau de bord / Synthèse'), ('proces_verbal', 'Procès-verbal / Compte-rendu'), ('situation', 'Situation financière'), ('autre', 'Autre document')], default='autre', max_length=30)),
                ('description', models.TextField(blank=True, help_text='Précisions sur ce type de document')),
                ('actif', models.BooleanField(default=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Type de document',
                'verbose_name_plural': 'Types de documents',
                'ordering': ['categorie', 'ordre', 'libelle'],
            },
        ),
        migrations.AddField(
            model_name='activite',
            name='cloture_commentaire',
            field=models.TextField(blank=True, verbose_name='Commentaire de clôture'),
        ),
        migrations.AddField(
            model_name='activite',
            name='cloture_motif',
            field=models.CharField(blank=True, choices=[('objectif_atteint', 'Objectif atteint ✓'), ('partiellement', 'Partiellement atteint'), ('non_atteint', 'Objectif non atteint'), ('annule', 'Activité annulée'), ('autre', 'Autre motif')], max_length=30, null=True, verbose_name='Motif de clôture'),
        ),
        migrations.CreateModel(
            name='DocumentActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.CharField(choices=[('non_commence', 'Non commencé'), ('en_cours', 'En cours de production'), ('finalise', 'Finalisé'), ('valide', 'Validé'), ('non_produit', 'Non produit')], default='non_commence', max_length=20)),
                ('observations', models.TextField(blank=True, help_text="Commentaires sur l'état de production")),
                ('date_prevue', models.DateField(blank=True, null=True, verbose_name='Date de production prévue')),
                ('date_realisation', models.DateField(blank=True, null=True, verbose_name='Date de réalisation effective')),
                ('mis_a_jour_le', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='operations.activite')),
                ('mis_a_jour_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_mis_a_jour', to=settings.AUTH_USER_MODEL)),
                ('type_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activite_docs', to='operations.typedocument')),
            ],
            options={
                'verbose_name': 'Document attendu',
                'verbose_name_plural': 'Documents attendus',
                'ordering': ['type_document__categorie', 'type_document__ordre'],
                'unique_together': {('activite', 'type_document')},
            },
        ),
    ]
